In [ ]:
import pandas as pd
import numpy as np
import torch

In [ ]:
# Normal dataset
normal_dataset_path = '../dataset/csv_output/normal_data_20251211_171740/normal_data_20251211_171740_essential.csv'
normal_dataset_2_path = '../dataset/csv_output/normal_data2_20251211_171736/normal_data2_20251211_171736_essential.csv'
normal_dataset_3_path = '../dataset/csv_output/normal_data3_20251211_171736/normal_data3_20251211_171736_essential.csv'
normal_dataset_4_path = '../dataset/csv_output/normal_data4_20251211_171737/normal_data4_20251211_171737_essential.csv'
normal_dataset_5_path = '../dataset/csv_output/normal_data5_20251211_171737/normal_data5_20251211_171737_essential.csv'
normal_dataset_6_path = '../dataset/csv_output/normal_data6_20251211_171739/normal_data6_20251211_171739_essential.csv'
normal_dataset_7_path = '../dataset/csv_output/normal_data7_20251211_171738/normal_data7_20251211_171738_essential.csv'
normal_dataset_8_path = '../dataset/csv_output/normal_data_compiled/normal1.csv'
normal_dataset_9_path = '../dataset/csv_output/normal_data_compiled/normal2.csv'
normal_dataset_10_path = '../dataset/csv_output/normal_data_compiled/normal3.csv'
# normal_dataset_11_path = './dataset/csv_output/normal_data_compiled/normal4.csv'
normal_dataset_12_path = '../dataset/csv_output/normal_data_compiled/normal5.csv'
normal_dataset_13_path = '../dataset/csv_output/normal_data_compiled/normal6.csv'
normal_dataset_14_path = '../dataset/csv_output/normal_data_compiled/normal7.csv'
normal_dataset_15_path = '  ./dataset/csv_output/normal_data_compiled/normal8.csv'


attack_attach_reject_path = '../dataset/csv_output/attach_reject_20251211_171644/attach_reject_20251211_171644_essential.csv'
attack_attach_reject_2_path = '../dataset/csv_output/attach_reject2_20251211_171715/attach_reject2_20251211_171715_essential.csv'

attack_auth_relay_sync_failure_path = '../dataset/csv_output/auth_relay_synch_failure_20251211_171608/auth_relay_synch_failure_20251211_171608_essential.csv'

attack_auth_failure_path = '../dataset/csv_output/authentication_failure_20251211_171624/authentication_failure_20251211_171624_essential.csv'

attack_capability_hijack_path = '../dataset/csv_output/capability_hijacking_20251211_171719/capability_hijacking_20251211_171719_essential.csv'

attack_detach_downgrade_path = '../dataset/csv_output/detach_downgrade_20251211_171622/detach_downgrade_20251211_171622_essential.csv'
attack_detach_downgrade_2_path = '../dataset/csv_output/detach_downgrade2_20251211_171641/detach_downgrade2_20251211_171641_essential.csv'
attack_detach_downgrade_3_path = '../dataset/csv_output/detach_downgrade3_20251211_171700/detach_downgrade3_20251211_171700_essential.csv'

attack_downgrade_tau_attack_path = '../dataset/csv_output/downgrade_tau_attack_20251211_171602/downgrade_tau_attack_20251211_171602_essential.csv'

attack_emm_information_path = '../dataset/csv_output/emm_information_20251211_171649/emm_information_20251211_171649_essential.csv'

attack_energy_depletion_path = '../dataset/csv_output/energy_depletion_20251211_171619/energy_depletion_20251211_171619_essential.csv'

attack_handover_hijacking_path = '../dataset/csv_output/handover_hijacking_20251211_171721/handover_hijacking_20251211_171721_essential.csv'

attack_imei_catching_path = '../dataset/csv_output/imei_catching_20251211_171723/imei_catching_20251211_171723_essential.csv'
attack_imsi_catching_path = '../dataset/csv_output/imsi_catching_20251211_171638/imsi_catching_20251211_171638_essential.csv'

attack_location_tracking_mr_path = '../dataset/csv_output/location_tracking_measurement_report_20251211_171717/location_tracking_measurement_report_20251211_171717_essential.csv'

attack_lullaby_attack_path = '../dataset/csv_output/lullaby_attack_rrc_reconfiguration_20251211_171714/lullaby_attack_rrc_reconfiguration_20251211_171714_essential.csv'
attack_lullaby_attack_2_path = '../dataset/csv_output/lullaby_attack_rrc_reconfiguration2_20251211_171602/lullaby_attack_rrc_reconfiguration2_20251211_171602_essential.csv'

attack_malformed_id_req_path = '../dataset/csv_output/malformed_identity_request_20251211_171619/malformed_identity_request_20251211_171619_essential.csv'

attack_null_enc_path = '../dataset/csv_output/null_encryption_20251211_171659/null_encryption_20251211_171659_essential.csv'

attack_paging_channel_hijacking_path = '../dataset/csv_output/paging_channel_hijacking1_20251211_171648/paging_channel_hijacking1_20251211_171648_essential.csv'
attack_paging_channel_hijacking_2_path = '../dataset/csv_output/paging_channel_hijacking2_20251211_171624/paging_channel_hijacking2_20251211_171624_essential.csv'

attack_panic_attack_path = '../dataset/csv_output/panic_attack_20251211_171706/panic_attack_20251211_171706_essential.csv'
attack_panic_attack_2_path = '../dataset/csv_output/panic_attack2_20251211_171632/panic_attack2_20251211_171632_essential.csv'

attack_replay_energy_depletion_auth_path = '../dataset/csv_output/replay_energy_depletion_auth_20251211_171630/replay_energy_depletion_auth_20251211_171630_essential.csv'

attack_rrc_reestablish_reject_path = '../dataset/csv_output/rrc_reestablish_reject_20251211_171629/rrc_reestablish_reject_20251211_171629_essential.csv'

attack_service_reject_path = '../dataset/csv_output/service_reject_20251211_171701/service_reject_20251211_171701_essential.csv'
attack_service_reject_2_path = '../dataset/csv_output/service_reject2_20251211_171718/service_reject2_20251211_171718_essential.csv'

attack_sib1_tac_path = '../dataset/csv_output/sib1_tac_attack_20251211_171609/sib1_tac_attack_20251211_171609_essential.csv'

attack_stealthy_kicking_off_path = '../dataset/csv_output/stealthy_kicking_off_20251211_171654/stealthy_kicking_off_20251211_171654_essential.csv'
attack_stealthy_kicking_off_2_path = '../dataset/csv_output/stealthy_kicking_off2_20251211_171720/stealthy_kicking_off2_20251211_171720_essential.csv'
attack_stealthy_kicking_off_3_path = '../dataset/csv_output/stealthy_kicking_off3_20251211_171705/stealthy_kicking_off3_20251211_171705_essential.csv'
attack_stealthy_kicking_off_4_path = '../dataset/csv_output/stealthy_kicking_off4_20251211_171651/stealthy_kicking_off4_20251211_171651_essential.csv'
attack_stealthy_kicking_off_5_path = '../dataset/csv_output/stealthy_kicking_off5_20251211_171644/stealthy_kicking_off5_20251211_171644_essential.csv'
attack_stealthy_kicking_off_6_path = '../dataset/csv_output/stealthy_kicking_off6_20251211_171627/stealthy_kicking_off6_20251211_171627_essential.csv'
attack_stealthy_kicking_off_7_path = '../dataset/csv_output/stealthy_kicking_off7_20251211_171626/stealthy_kicking_off7_20251211_171626_essential.csv'


attack_tau_reject_path = '../dataset/csv_output/tau_reject_20251211_171651/tau_reject_20251211_171651_essential.csv'
attack_tau_reject_nmap_path = '../dataset/csv_output/tau_reject_nmap_20251211_171656/tau_reject_nmap_20251211_171656_essential.csv'

In [ ]:
# Helper to read CSV or return empty DataFrame if file is empty/missing
def safe_read_csv(path):
    try:
        return pd.read_csv(path)
    except (pd.errors.EmptyDataError, FileNotFoundError):
        print(f"Warning: {path} is empty or missing, skipping.")
        return pd.DataFrame()

normal_dataset_1 = safe_read_csv(normal_dataset_path)
normal_dataset_2 = safe_read_csv(normal_dataset_2_path)
normal_dataset_3 = safe_read_csv(normal_dataset_3_path)
normal_dataset_4 = safe_read_csv(normal_dataset_4_path)
normal_dataset_5 = safe_read_csv(normal_dataset_5_path)
normal_dataset_6 = safe_read_csv(normal_dataset_6_path)
normal_dataset_7 = safe_read_csv(normal_dataset_7_path)
normal_dataset_8 = safe_read_csv(normal_dataset_8_path)
normal_dataset_9 = safe_read_csv(normal_dataset_9_path)
normal_dataset_10 = safe_read_csv(normal_dataset_10_path)
# normal_dataset_11 = safe_read_csv(normal_dataset_11_path)
normal_dataset_12 = safe_read_csv(normal_dataset_12_path)
normal_dataset_13 = safe_read_csv(normal_dataset_13_path)
normal_dataset_14 = safe_read_csv(normal_dataset_14_path)
normal_dataset_15 = safe_read_csv(normal_dataset_15_path)

attack_attach_reject = pd.read_csv(attack_attach_reject_path)
attack_attach_reject_2 = pd.read_csv(attack_attach_reject_2_path)

attack_auth_relay_sync_failure = pd.read_csv(attack_auth_relay_sync_failure_path)

attack_auth_failure = pd.read_csv(attack_auth_failure_path)

attack_capability_hijack = pd.read_csv(attack_capability_hijack_path)

attack_detach_downgrade = pd.read_csv(attack_detach_downgrade_path)

attack_detach_downgrade = pd.read_csv(attack_detach_downgrade_path)
attack_detach_downgrade_2 = pd.read_csv(attack_detach_downgrade_2_path)
attack_detach_downgrade_3 = pd.read_csv(attack_detach_downgrade_3_path)

attack_downgrade_tau_attack = pd.read_csv(attack_downgrade_tau_attack_path)

attack_emm_information = pd.read_csv(attack_emm_information_path)

attack_energy_depletion = pd.read_csv(attack_energy_depletion_path)

attack_handover_hijacking = pd.read_csv(attack_handover_hijacking_path)

attack_imei_catching = pd.read_csv(attack_imei_catching_path)

attack_imsi_catching = pd.read_csv(attack_imsi_catching_path)

attack_location_tracking_mr = pd.read_csv(attack_location_tracking_mr_path)

attack_lullaby_attack = pd.read_csv(attack_lullaby_attack_path)
attack_lullaby_attack_2 = pd.read_csv(attack_lullaby_attack_2_path)

attack_malformed_id_req = pd.read_csv(attack_malformed_id_req_path)

attack_null_enc = pd.read_csv(attack_null_enc_path)

attack_paging_channel_hijacking = pd.read_csv(attack_paging_channel_hijacking_path)
attack_paging_channel_hijacking_2 = pd.read_csv(attack_paging_channel_hijacking_2_path)

attack_panic_attack = pd.read_csv(attack_panic_attack_path)
attack_panic_attack_2 = pd.read_csv(attack_panic_attack_2_path)

attack_sib1_tac = pd.read_csv(attack_sib1_tac_path)

attack_stealthy_kicking_off = pd.read_csv(attack_stealthy_kicking_off_path)
attack_stealthy_kicking_off_2 = pd.read_csv(attack_stealthy_kicking_off_2_path)
attack_stealthy_kicking_off_3 = pd.read_csv(attack_stealthy_kicking_off_3_path)
attack_stealthy_kicking_off_4 = pd.read_csv(attack_stealthy_kicking_off_4_path)
attack_stealthy_kicking_off_5 = pd.read_csv(attack_stealthy_kicking_off_5_path)
attack_stealthy_kicking_off_6 = pd.read_csv(attack_stealthy_kicking_off_6_path)
attack_stealthy_kicking_off_7 = pd.read_csv(attack_stealthy_kicking_off_7_path)

attack_tau_reject = pd.read_csv(attack_tau_reject_path)
attack_tau_reject_nmap = pd.read_csv(attack_tau_reject_nmap_path)

Warning:   ./dataset/csv_output/normal_data_compiled/normal8.csv is empty or missing, skipping.

In [ ]:
normal_dataset = pd.concat([normal_dataset_1,
                            normal_dataset_2,
                            normal_dataset_3,
                            normal_dataset_4,
                            normal_dataset_5,
                            normal_dataset_6,
                            normal_dataset_7,
                            normal_dataset_8,
                            normal_dataset_9,
                            normal_dataset_10,
                            # normal_dataset_11,
                            normal_dataset_12,
                            normal_dataset_13,
                            normal_dataset_14,
                            normal_dataset_15,
                            ],axis=0,ignore_index=True)

In [ ]:
# 25 attack  = 5000

# 1 attack = 200
# 1 normal : 514

skip = 40
n = 400

attack_dataset = pd.concat([
    attack_attach_reject.iloc[skip:skip+n],
    attack_attach_reject_2.iloc[skip:skip+n],
    attack_auth_relay_sync_failure.iloc[skip:skip+n],
    attack_auth_failure.iloc[skip:skip+n],
    attack_capability_hijack.iloc[skip:skip+n],
    attack_detach_downgrade.iloc[skip:skip+n],
    attack_detach_downgrade_2.iloc[skip:skip+n],
    attack_detach_downgrade_3.iloc[skip:skip+n],
    attack_downgrade_tau_attack.iloc[skip:skip+n],
    attack_emm_information.iloc[skip:skip+n],
    attack_energy_depletion.iloc[skip:skip+n],
    attack_handover_hijacking.iloc[skip:skip+n],
    attack_imei_catching.iloc[skip:skip+n],
    attack_imsi_catching.iloc[skip:skip+n],
    attack_location_tracking_mr.iloc[skip:skip+n],
    attack_lullaby_attack.iloc[skip:skip+n],
    attack_lullaby_attack_2.iloc[skip:skip+n],
    attack_malformed_id_req.iloc[skip:skip+n],
    attack_null_enc.iloc[skip:skip+n],
    attack_paging_channel_hijacking.iloc[skip:skip+n],
    attack_paging_channel_hijacking_2.iloc[skip:skip+n],
    attack_panic_attack.iloc[skip:skip+n],
    attack_sib1_tac.iloc[skip:skip+n],
    attack_stealthy_kicking_off.iloc[skip:skip+n],
    attack_stealthy_kicking_off_2.iloc[skip:skip+n],
    attack_stealthy_kicking_off_3.iloc[skip:skip+n],
    attack_tau_reject.iloc[skip:skip+n],
    attack_tau_reject_nmap.iloc[skip:skip+n]
],axis=0,ignore_index=True)

In [ ]:
attack_dataset

,e212_gummei_mcc_show,e212_gummei_mcc_value,e212_gummei_mcc_size,e212_gummei_mcc_pos,e212_gummei_mnc_show,e212_gummei_mnc_value,e212_gummei_mnc_size,e212_gummei_mnc_pos,e212_imsi_show,e212_imsi_value,...,nr-rrc_ul_ccch_message_message_size,nr-rrc_ul_ccch_message_message_pos,nr-rrc_ul_dcch_message_message_show,nr-rrc_ul_dcch_message_message_value,nr-rrc_ul_dcch_message_message_size,nr-rrc_ul_dcch_message_message_pos,nr-rrc_valuetag_show,nr-rrc_valuetag_value,nr-rrc_valuetag_size,nr-rrc_valuetag_pos
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6527,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6528,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6529,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6530,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
6531,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [ ]:
normal_dataset

,e212_gummei_mcc_show,e212_gummei_mcc_value,e212_gummei_mcc_size,e212_gummei_mcc_pos,e212_gummei_mnc_show,e212_gummei_mnc_value,e212_gummei_mnc_size,e212_gummei_mnc_pos,e212_imsi_show,e212_imsi_value,...,nr-rrc_ul_ccch_message_message_size,nr-rrc_ul_ccch_message_message_pos,nr-rrc_ul_dcch_message_message_show,nr-rrc_ul_dcch_message_message_value,nr-rrc_ul_dcch_message_message_size,nr-rrc_ul_dcch_message_message_pos,nr-rrc_valuetag_show,nr-rrc_valuetag_value,nr-rrc_valuetag_size,nr-rrc_valuetag_pos
0,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
814,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
815,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
816,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
817,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
818,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [ ]:
cols_to_remove = [
    "timestamp",
    "message_index",
    "packet_type",
    "direction",
    "info"
]

normal_dataset_clean = normal_dataset.drop(columns=cols_to_remove, errors="ignore")
attack_dataset_clean = attack_dataset.drop(columns=cols_to_remove, errors="ignore")

In [ ]:
normal_dataset_clean["label"] = 0
attack_dataset_clean["label"] = 1

In [ ]:
mixed_cols = [
    col for col in attack_dataset_clean.columns 
    
]

print("Mixed-type columns:", mixed_cols)

Mixed-type columns: ['e212_gummei_mcc_show', 'e212_gummei_mcc_value', 'e212_gummei_mcc_size', 'e212_gummei_mcc_pos', 'e212_gummei_mnc_show', 'e212_gummei_mnc_value', 'e212_gummei_mnc_size', 'e212_gummei_mnc_pos', 'e212_imsi_show', 'e212_imsi_value', 'e212_imsi_size', 'e212_imsi_pos', 'e212_mcc_show', 'e212_mcc_value', 'e212_mcc_size', 'e212_mcc_pos', 'e212_mnc_show', 'e212_mnc_value', 'e212_mnc_size', 'e212_mnc_pos', 'e212_tai_mcc_show', 'e212_tai_mcc_value', 'e212_tai_mcc_size', 'e212_tai_mcc_pos', 'e212_tai_mnc_show', 'e212_tai_mnc_value', 'e212_tai_mnc_size', 'e212_tai_mnc_pos', 'gsm_a_dtap_autn_show', 'gsm_a_dtap_autn_value', 'gsm_a_dtap_autn_size', 'gsm_a_dtap_autn_pos', 'gsm_a_dtap_autn_amf_show', 'gsm_a_dtap_autn_amf_value', 'gsm_a_dtap_autn_amf_size', 'gsm_a_dtap_autn_amf_pos', 'gsm_a_dtap_autn_mac_show', 'gsm_a_dtap_autn_mac_value', 'gsm_a_dtap_autn_mac_size', 'gsm_a_dtap_autn_mac_pos', 'gsm_a_dtap_autn_sqn_xor_ak_show', 'gsm_a_dtap_autn_sqn_xor_ak_value', 'gsm_a_dtap_autn_sqn_xor_ak_size', 'gsm_a_dtap_autn_sqn_xor_ak_pos', 'gsm_a_dtap_rand_show', 'gsm_a_dtap_rand_value', 'gsm_a_dtap_rand_size', 'gsm_a_dtap_rand_pos', 'gsm_a_ie_mobileid_type_show', 'gsm_a_ie_mobileid_type_value', 'gsm_a_ie_mobileid_type_size', 'gsm_a_ie_mobileid_type_pos', 'gsm_a_imeisv_show', 'gsm_a_imeisv_value', 'gsm_a_imeisv_size', 'gsm_a_imeisv_pos', 'gsm_a_key_seq_show', 'gsm_a_key_seq_value', 'gsm_a_key_seq_size', 'gsm_a_key_seq_pos', 'gsm_a_l3_protocol_discriminator_show', 'gsm_a_l3_protocol_discriminator_value', 'gsm_a_l3_protocol_discriminator_size', 'gsm_a_l3_protocol_discriminator_pos', 'gsm_a_lac_show', 'gsm_a_lac_value', 'gsm_a_lac_size', 'gsm_a_lac_pos', 'gsm_a_oddevenind_show', 'gsm_a_oddevenind_value', 'gsm_a_oddevenind_size', 'gsm_a_oddevenind_pos', 'gsm_a_skip_ind_show', 'gsm_a_skip_ind_value', 'gsm_a_skip_ind_size', 'gsm_a_skip_ind_pos', 'lte-rrc_accessstratumrelease_show', 'lte-rrc_accessstratumrelease_value', 'lte-rrc_accessstratumrelease_size', 'lte-rrc_accessstratumrelease_pos', 'lte-rrc_alpha_show', 'lte-rrc_alpha_value', 'lte-rrc_alpha_size', 'lte-rrc_alpha_pos', 'lte-rrc_alternativetbs_indices_r12_show', 'lte-rrc_alternativetbs_indices_r12_value', 'lte-rrc_alternativetbs_indices_r12_size', 'lte-rrc_alternativetbs_indices_r12_pos', 'lte-rrc_bandcombinationlisteutra_r10_show', 'lte-rrc_bandcombinationlisteutra_r10_value', 'lte-rrc_bandcombinationlisteutra_r10_size', 'lte-rrc_bandcombinationlisteutra_r10_pos', 'lte-rrc_bandcombinationparameters_r10_show', 'lte-rrc_bandcombinationparameters_r10_value', 'lte-rrc_bandcombinationparameters_r10_size', 'lte-rrc_bandcombinationparameters_r10_pos', 'lte-rrc_c1_show', 'lte-rrc_c1_value', 'lte-rrc_c1_size', 'lte-rrc_c1_pos', 'lte-rrc_c_rnti_show', 'lte-rrc_c_rnti_value', 'lte-rrc_c_rnti_size', 'lte-rrc_c_rnti_pos', 'lte-rrc_ca_bandwidthclassdl_r10_show', 'lte-rrc_ca_bandwidthclassdl_r10_value', 'lte-rrc_ca_bandwidthclassdl_r10_size', 'lte-rrc_ca_bandwidthclassdl_r10_pos', 'lte-rrc_ca_bandwidthclassul_r10_show', 'lte-rrc_ca_bandwidthclassul_r10_value', 'lte-rrc_ca_bandwidthclassul_r10_size', 'lte-rrc_ca_bandwidthclassul_r10_pos', 'lte-rrc_carrierfreq_show', 'lte-rrc_carrierfreq_value', 'lte-rrc_carrierfreq_size', 'lte-rrc_carrierfreq_pos', 'lte-rrc_cellbarred_show', 'lte-rrc_cellbarred_value', 'lte-rrc_cellbarred_size', 'lte-rrc_cellbarred_pos', 'lte-rrc_cellidentity_show', 'lte-rrc_cellidentity_value', 'lte-rrc_cellidentity_size', 'lte-rrc_cellidentity_pos', 'lte-rrc_cellreselectionpriority_show', 'lte-rrc_cellreselectionpriority_value', 'lte-rrc_cellreselectionpriority_size', 'lte-rrc_cellreselectionpriority_pos', 'lte-rrc_cellreservedforoperatoruse_show', 'lte-rrc_cellreservedforoperatoruse_value', 'lte-rrc_cellreservedforoperatoruse_size', 'lte-rrc_cellreservedforoperatoruse_pos', 'lte-rrc_cipheringalgorithm_show', 'lte-rrc_cipheringalgorithm_value', 'lte-rrc_cipheringalgorithm_size', 'lte-rrc_cipheringalgorithm_pos', 'lte-rrc_cn_domain_show', 'lte-rrc_cn_domain_value', 'lte-rrc_cn_domain_size', 'lte-rrc_cn_domain_pos', 'lte-rrc_connectionfailuretype_r10_show', 'lte-rrc_connectionfailuretype_r10_value', 'lte-rrc_connectionfailuretype_r10_size', 'lte-rrc_connectionfailuretype_r10_pos', 'lte-rrc_connestfailcount_r12_show', 'lte-rrc_connestfailcount_r12_value', 'lte-rrc_connestfailcount_r12_size', 'lte-rrc_connestfailcount_r12_pos', 'lte-rrc_connestfailoffsetvalidity_r12_show', 'lte-rrc_connestfailoffsetvalidity_r12_value', 'lte-rrc_connestfailoffsetvalidity_r12_size', 'lte-rrc_connestfailoffsetvalidity_r12_pos', 'lte-rrc_criticalextensions_show', 'lte-rrc_criticalextensions_value', 'lte-rrc_criticalextensions_size', 'lte-rrc_criticalextensions_pos', 'lte-rrc_dedicatedinfonas_show', 'lte-rrc_dedicatedinfonas_value', 'lte-rrc_dedicatedinfonas_size', 'lte-rrc_dedicatedinfonas_pos', 'lte-rrc_dedicatedinfonaslist_show', 'lte-rrc_dedicatedinfonaslist_value', 'lte-rrc_dedicatedinfonaslist_size', 'lte-rrc_dedicatedinfonaslist_pos', 'lte-rrc_dedicatedinfotype_show', 'lte-rrc_dedicatedinfotype_value', 'lte-rrc_dedicatedinfotype_size', 'lte-rrc_dedicatedinfotype_pos', 'lte-rrc_defaultpagingcycle_show', 'lte-rrc_defaultpagingcycle_value', 'lte-rrc_defaultpagingcycle_size', 'lte-rrc_defaultpagingcycle_pos', 'lte-rrc_deltaf_pucch_format1_show', 'lte-rrc_deltaf_pucch_format1_value', 'lte-rrc_deltaf_pucch_format1_size', 'lte-rrc_deltaf_pucch_format1_pos', 'lte-rrc_deltaf_pucch_format1b_show', 'lte-rrc_deltaf_pucch_format1b_value', 'lte-rrc_deltaf_pucch_format1b_size', 'lte-rrc_deltaf_pucch_format1b_pos', 'lte-rrc_deltaf_pucch_format2_show', 'lte-rrc_deltaf_pucch_format2_value', 'lte-rrc_deltaf_pucch_format2_size', 'lte-rrc_deltaf_pucch_format2_pos', 'lte-rrc_deltaf_pucch_format2a_show', 'lte-rrc_deltaf_pucch_format2a_value', 'lte-rrc_deltaf_pucch_format2a_size', 'lte-rrc_deltaf_pucch_format2a_pos', 'lte-rrc_deltaf_pucch_format2b_show', 'lte-rrc_deltaf_pucch_format2b_value', 'lte-rrc_deltaf_pucch_format2b_size', 'lte-rrc_deltaf_pucch_format2b_pos', 'lte-rrc_deltapucch_shift_show', 'lte-rrc_deltapucch_shift_value', 'lte-rrc_deltapucch_shift_size', 'lte-rrc_deltapucch_shift_pos', 'lte-rrc_dl_256qam_r12_show', 'lte-rrc_dl_256qam_r12_value', 'lte-rrc_dl_256qam_r12_size', 'lte-rrc_dl_256qam_r12_pos', 'lte-rrc_dl_bandwidth_show', 'lte-rrc_dl_bandwidth_value', 'lte-rrc_dl_bandwidth_size', 'lte-rrc_dl_bandwidth_pos', 'lte-rrc_dl_carrierfreq_show', 'lte-rrc_dl_carrierfreq_value', 'lte-rrc_dl_carrierfreq_size', 'lte-rrc_dl_carrierfreq_pos', 'lte-rrc_dl_ccch_message_message_show', 'lte-rrc_dl_ccch_message_message_value', 'lte-rrc_dl_ccch_message_message_size', 'lte-rrc_dl_ccch_message_message_pos', 'lte-rrc_dl_dcch_message_message_show', 'lte-rrc_dl_dcch_message_message_value', 'lte-rrc_dl_dcch_message_message_size', 'lte-rrc_dl_dcch_message_message_pos', 'lte-rrc_drb_identity_show', 'lte-rrc_drb_identity_value', 'lte-rrc_drb_identity_size', 'lte-rrc_drb_identity_pos', 'lte-rrc_en_dc_r15_show', 'lte-rrc_en_dc_r15_value', 'lte-rrc_en_dc_r15_size', 'lte-rrc_en_dc_r15_pos', 'lte-rrc_enable64qam_show', 'lte-rrc_enable64qam_value', 'lte-rrc_enable64qam_size', 'lte-rrc_enable64qam_pos', 'lte-rrc_eps_beareridentity_show', 'lte-rrc_eps_beareridentity_value', 'lte-rrc_eps_beareridentity_size', 'lte-rrc_eps_beareridentity_pos', 'lte-rrc_establishmentcause_show', 'lte-rrc_establishmentcause_value', 'lte-rrc_establishmentcause_size', 'lte-rrc_establishmentcause_pos', 'lte-rrc_failedpcellid_r10_show', 'lte-rrc_failedpcellid_r10_value', 'lte-rrc_failedpcellid_r10_size', 'lte-rrc_failedpcellid_r10_pos', 'lte-rrc_featuregroupindicators_show', 'lte-rrc_featuregroupindicators_value', 'lte-rrc_featuregroupindicators_size', 'lte-rrc_featuregroupindicators_pos', 'lte-rrc_freqbandindicator_show', 'lte-rrc_freqbandindicator_value', 'lte-rrc_freqbandindicator_size', 'lte-rrc_freqbandindicator_pos', 'lte-rrc_gummei_type_r10_show', 'lte-rrc_gummei_type_r10_value', 'lte-rrc_gummei_type_r10_size', 'lte-rrc_gummei_type_r10_pos', 'lte-rrc_halfduplex_show', 'lte-rrc_halfduplex_value', 'lte-rrc_halfduplex_size', 'lte-rrc_halfduplex_pos', 'lte-rrc_ims_emergencysupport_r9_show', 'lte-rrc_ims_emergencysupport_r9_value', 'lte-rrc_ims_emergencysupport_r9_size', 'lte-rrc_ims_emergencysupport_r9_pos', 'lte-rrc_integrityprotalgorithm_show', 'lte-rrc_integrityprotalgorithm_value', 'lte-rrc_integrityprotalgorithm_size', 'lte-rrc_integrityprotalgorithm_pos', 'lte-rrc_interfreqbandlist_show', 'lte-rrc_interfreqbandlist_value', 'lte-rrc_interfreqbandlist_size', 'lte-rrc_interfreqbandlist_pos', 'lte-rrc_interfreqcarrierfreqlist_show', 'lte-rrc_interfreqcarrierfreqlist_value', 'lte-rrc_interfreqcarrierfreqlist_size', 'lte-rrc_interfreqcarrierfreqlist_pos', 'lte-rrc_interfreqneedforgaps_show', 'lte-rrc_interfreqneedforgaps_value', 'lte-rrc_interfreqneedforgaps_size', 'lte-rrc_interfreqneedforgaps_pos', 'lte-rrc_interrat_bandlist_show', 'lte-rrc_interrat_bandlist_value', 'lte-rrc_interrat_bandlist_size', 'lte-rrc_interrat_bandlist_pos', 'lte-rrc_interrat_needforgaps_show', 'lte-rrc_interrat_needforgaps_value', 'lte-rrc_interrat_needforgaps_size', 'lte-rrc_interrat_needforgaps_pos', 'lte-rrc_intrafreqreselection_show', 'lte-rrc_intrafreqreselection_value', 'lte-rrc_intrafreqreselection_size', 'lte-rrc_intrafreqreselection_pos', 'lte-rrc_latenoncriticalextension_show', 'lte-rrc_latenoncriticalextension_value', 'lte-rrc_latenoncriticalextension_size', 'lte-rrc_latenoncriticalextension_pos', 'lte-rrc_loggedmeasurementsidle_r10_show', 'lte-rrc_loggedmeasurementsidle_r10_value', 'lte-rrc_loggedmeasurementsidle_r10_size', 'lte-rrc_loggedmeasurementsidle_r10_pos', 'lte-rrc_logicalchannelidentity_show', 'lte-rrc_logicalchannelidentity_value', 'lte-rrc_logicalchannelidentity_size', 'lte-rrc_logicalchannelidentity_pos', 'lte-rrc_m_tmsi_show', 'lte-rrc_m_tmsi_value', 'lte-rrc_m_tmsi_size', 'lte-rrc_m_tmsi_pos', 'lte-rrc_mac_contentionresolutiontimer_show', 'lte-rrc_mac_contentionresolutiontimer_value', 'lte-rrc_mac_contentionresolutiontimer_size', 'lte-rrc_mac_contentionresolutiontimer_pos', 'lte-rrc_mac_mainconfig_show', 'lte-rrc_mac_mainconfig_value', 'lte-rrc_mac_mainconfig_size', 'lte-rrc_mac_mainconfig_pos', 'lte-rrc_maxharq_msg3tx_show', 'lte-rrc_maxharq_msg3tx_value', 'lte-rrc_maxharq_msg3tx_size', 'lte-rrc_maxharq_msg3tx_pos', 'lte-rrc_maxharq_tx_show', 'lte-rrc_maxharq_tx_value', 'lte-rrc_maxharq_tx_size', 'lte-rrc_maxharq_tx_pos', 'lte-rrc_mcc_show', 'lte-rrc_mcc_value', 'lte-rrc_mcc_size', 'lte-rrc_mcc_pos', 'lte-rrc_mmec_show', 'lte-rrc_mmec_value', 'lte-rrc_mmec_size', 'lte-rrc_mmec_pos', 'lte-rrc_mmegi_show', 'lte-rrc_mmegi_value', 'lte-rrc_mmegi_size', 'lte-rrc_mmegi_pos', 'lte-rrc_mnc_show', 'lte-rrc_mnc_value', 'lte-rrc_mnc_size', 'lte-rrc_mnc_pos', 'lte-rrc_mobilitystate_r12_show', 'lte-rrc_mobilitystate_r12_value', 'lte-rrc_mobilitystate_r12_size', 'lte-rrc_mobilitystate_r12_pos', 'lte-rrc_n1pucch_an_show', 'lte-rrc_n1pucch_an_value', 'lte-rrc_n1pucch_an_size', 'lte-rrc_n1pucch_an_pos', 'lte-rrc_n310_show', 'lte-rrc_n310_value', 'lte-rrc_n310_size', 'lte-rrc_n310_pos', 'lte-rrc_n311_show', 'lte-rrc_n311_value', 'lte-rrc_n311_size', 'lte-rrc_n311_pos', 'lte-rrc_neighcellconfig_show', 'lte-rrc_neighcellconfig_value', 'lte-rrc_neighcellconfig_size', 'lte-rrc_neighcellconfig_pos', 'lte-rrc_nexthopchainingcount_show', 'lte-rrc_nexthopchainingcount_value', 'lte-rrc_nexthopchainingcount_size', 'lte-rrc_nexthopchainingcount_pos', 'lte-rrc_p0_nominalpucch_show', 'lte-rrc_p0_nominalpucch_value', 'lte-rrc_p0_nominalpucch_size', 'lte-rrc_p0_nominalpucch_pos', 'lte-rrc_p0_nominalpusch_show', 'lte-rrc_p0_nominalpusch_value', 'lte-rrc_p0_nominalpusch_size', 'lte-rrc_p0_nominalpusch_pos', 'lte-rrc_p_max_show', 'lte-rrc_p_max_value', 'lte-rrc_p_max_size', 'lte-rrc_p_max_pos', 'lte-rrc_pcch_message_message_show', 'lte-rrc_pcch_message_message_value', 'lte-rrc_pcch_message_message_size', 'lte-rrc_pcch_message_message_pos', 'lte-rrc_periodicbsr_timer_show', 'lte-rrc_periodicbsr_timer_value', 'lte-rrc_periodicbsr_timer_size', 'lte-rrc_periodicbsr_timer_pos', 'lte-rrc_physcellid_show', 'lte-rrc_physcellid_value', 'lte-rrc_physcellid_size', 'lte-rrc_physcellid_pos', 'lte-rrc_q_hyst_show', 'lte-rrc_q_hyst_value', 'lte-rrc_q_hyst_size', 'lte-rrc_q_hyst_pos', 'lte-rrc_q_offsetfreq_show', 'lte-rrc_q_offsetfreq_value', 'lte-rrc_q_offsetfreq_size', 'lte-rrc_q_offsetfreq_pos', 'lte-rrc_q_rxlevmin_show', 'lte-rrc_q_rxlevmin_value', 'lte-rrc_q_rxlevmin_size', 'lte-rrc_q_rxlevmin_pos', 'lte-rrc_rach_report_r9_show', 'lte-rrc_rach_report_r9_value', 'lte-rrc_rach_report_r9_size', 'lte-rrc_rach_report_r9_pos', 'lte-rrc_rach_reportreq_r9_show', 'lte-rrc_rach_reportreq_r9_value', 'lte-rrc_rach_reportreq_r9_size', 'lte-rrc_rach_reportreq_r9_pos', 'lte-rrc_randomvalue_show', 'lte-rrc_randomvalue_value', 'lte-rrc_randomvalue_size', 'lte-rrc_randomvalue_pos', 'lte-rrc_rat_type_show', 'lte-rrc_rat_type_value', 'lte-rrc_rat_type_size', 'lte-rrc_rat_type_pos', 'lte-rrc_reestablishmentcause_show', 'lte-rrc_reestablishmentcause_value', 'lte-rrc_reestablishmentcause_size', 'lte-rrc_reestablishmentcause_pos', 'lte-rrc_referencesignalpower_show', 'lte-rrc_referencesignalpower_value', 'lte-rrc_referencesignalpower_size', 'lte-rrc_referencesignalpower_pos', 'lte-rrc_releasecause_show', 'lte-rrc_releasecause_value', 'lte-rrc_releasecause_size', 'lte-rrc_releasecause_pos', 'lte-rrc_retxbsr_timer_show', 'lte-rrc_retxbsr_timer_value', 'lte-rrc_retxbsr_timer_size', 'lte-rrc_retxbsr_timer_pos', 'lte-rrc_rlf_cause_r11_show', 'lte-rrc_rlf_cause_r11_value', 'lte-rrc_rlf_cause_r11_size', 'lte-rrc_rlf_cause_r11_pos', 'lte-rrc_rlf_infoavailable_r10_show', 'lte-rrc_rlf_infoavailable_r10_value', 'lte-rrc_rlf_infoavailable_r10_size', 'lte-rrc_rlf_infoavailable_r10_pos', 'lte-rrc_rlf_infoavailable_r9_show', 'lte-rrc_rlf_infoavailable_r9_value', 'lte-rrc_rlf_infoavailable_r9_size', 'lte-rrc_rlf_infoavailable_r9_pos', 'lte-rrc_rlf_reportreq_r9_show', 'lte-rrc_rlf_reportreq_r9_value', 'lte-rrc_rlf_reportreq_r9_size', 'lte-rrc_rlf_reportreq_r9_pos', 'lte-rrc_rrc_transactionidentifier_show', 'lte-rrc_rrc_transactionidentifier_value', 'lte-rrc_rrc_transactionidentifier_size', 'lte-rrc_rrc_transactionidentifier_pos', 'lte-rrc_rsrpresult_r9_show', 'lte-rrc_rsrpresult_r9_value', 'lte-rrc_rsrpresult_r9_size', 'lte-rrc_rsrpresult_r9_pos', 'lte-rrc_rsrqresult_r9_show', 'lte-rrc_rsrqresult_r9_value', 'lte-rrc_rsrqresult_r9_size', 'lte-rrc_rsrqresult_r9_pos', 'lte-rrc_s_intrasearch_show', 'lte-rrc_s_intrasearch_value', 'lte-rrc_s_intrasearch_size', 'lte-rrc_s_intrasearch_pos', 'lte-rrc_s_nonintrasearch_show', 'lte-rrc_s_nonintrasearch_value', 'lte-rrc_s_nonintrasearch_size', 'lte-rrc_s_nonintrasearch_pos', 'lte-rrc_schedulinginfolist_show', 'lte-rrc_schedulinginfolist_value', 'lte-rrc_schedulinginfolist_size', 'lte-rrc_schedulinginfolist_pos', 'lte-rrc_selectedplmn_identity_show', 'lte-rrc_selectedplmn_identity_value', 'lte-rrc_selectedplmn_identity_size', 'lte-rrc_selectedplmn_identity_pos', 'lte-rrc_shortmac_i_show', 'lte-rrc_shortmac_i_value', 'lte-rrc_shortmac_i_size', 'lte-rrc_shortmac_i_pos', 'lte-rrc_si_windowlength_show', 'lte-rrc_si_windowlength_value', 'lte-rrc_si_windowlength_size', 'lte-rrc_si_windowlength_pos', 'lte-rrc_srb_identity_show', 'lte-rrc_srb_identity_value', 'lte-rrc_srb_identity_size', 'lte-rrc_srb_identity_pos', 'lte-rrc_supportedbandcombination_r10_show', 'lte-rrc_supportedbandcombination_r10_value', 'lte-rrc_supportedbandcombination_r10_size', 'lte-rrc_supportedbandcombination_r10_pos', 'lte-rrc_supportedbandcombinationext_r10_show', 'lte-rrc_supportedbandcombinationext_r10_value', 'lte-rrc_supportedbandcombinationext_r10_size', 'lte-rrc_supportedbandcombinationext_r10_pos', 'lte-rrc_supportedbandgeran_show', 'lte-rrc_supportedbandgeran_value', 'lte-rrc_supportedbandgeran_size', 'lte-rrc_supportedbandgeran_pos', 'lte-rrc_supportedbandlisteutra_show', 'lte-rrc_supportedbandlisteutra_value', 'lte-rrc_supportedbandlisteutra_size', 'lte-rrc_supportedbandlisteutra_pos', 'lte-rrc_supportedbandlistgeran_show', 'lte-rrc_supportedbandlistgeran_value', 'lte-rrc_supportedbandlistgeran_size', 'lte-rrc_supportedbandlistgeran_pos', 'lte-rrc_supportedbandlistutra_fdd_show', 'lte-rrc_supportedbandlistutra_fdd_value', 'lte-rrc_supportedbandlistutra_fdd_size', 'lte-rrc_supportedbandlistutra_fdd_pos', 'lte-rrc_supportedbandutra_fdd_show', 'lte-rrc_supportedbandutra_fdd_value', 'lte-rrc_supportedbandutra_fdd_size', 'lte-rrc_supportedbandutra_fdd_pos', 'lte-rrc_supportedmimo_capabilitydl_r10_show', 'lte-rrc_supportedmimo_capabilitydl_r10_value', 'lte-rrc_supportedmimo_capabilitydl_r10_size', 'lte-rrc_supportedmimo_capabilitydl_r10_pos', 'lte-rrc_systemframenumber_show', 'lte-rrc_systemframenumber_value', 'lte-rrc_systemframenumber_size', 'lte-rrc_systemframenumber_pos', 'lte-rrc_systeminfovaluetag_show', 'lte-rrc_systeminfovaluetag_value', 'lte-rrc_systeminfovaluetag_size', 'lte-rrc_systeminfovaluetag_pos', 'lte-rrc_t300_show', 'lte-rrc_t300_value', 'lte-rrc_t300_size', 'lte-rrc_t300_pos', 'lte-rrc_t301_show', 'lte-rrc_t301_value', 'lte-rrc_t301_size', 'lte-rrc_t301_pos', 'lte-rrc_t310_show', 'lte-rrc_t310_value', 'lte-rrc_t310_size', 'lte-rrc_t310_pos', 'lte-rrc_t311_show', 'lte-rrc_t311_value', 'lte-rrc_t311_size', 'lte-rrc_t311_pos', 'lte-rrc_t320_show', 'lte-rrc_t320_value', 'lte-rrc_t320_size', 'lte-rrc_t320_pos', 'lte-rrc_t_reselectioneutra_show', 'lte-rrc_t_reselectioneutra_value', 'lte-rrc_t_reselectioneutra_size', 'lte-rrc_t_reselectioneutra_pos', 'lte-rrc_tac_failedpcell_r12_show', 'lte-rrc_tac_failedpcell_r12_value', 'lte-rrc_tac_failedpcell_r12_size', 'lte-rrc_tac_failedpcell_r12_pos', 'lte-rrc_threshservinglow_show', 'lte-rrc_threshservinglow_value', 'lte-rrc_threshservinglow_size', 'lte-rrc_threshservinglow_pos', 'lte-rrc_threshx_high_show', 'lte-rrc_threshx_high_value', 'lte-rrc_threshx_high_size', 'lte-rrc_threshx_high_pos', 'lte-rrc_threshx_low_show', 'lte-rrc_threshx_low_value', 'lte-rrc_threshx_low_size', 'lte-rrc_threshx_low_pos', 'lte-rrc_timesincefailure_r11_show', 'lte-rrc_timesincefailure_r11_value', 'lte-rrc_timesincefailure_r11_size', 'lte-rrc_timesincefailure_r11_pos', 'lte-rrc_trackingareacode_show', 'lte-rrc_trackingareacode_value', 'lte-rrc_trackingareacode_size', 'lte-rrc_trackingareacode_pos', 'lte-rrc_transmissionmode_show', 'lte-rrc_transmissionmode_value', 'lte-rrc_transmissionmode_size', 'lte-rrc_transmissionmode_pos', 'lte-rrc_ttibundling_show', 'lte-rrc_ttibundling_value', 'lte-rrc_ttibundling_size', 'lte-rrc_ttibundling_pos', 'lte-rrc_ue_capabilityrat_containerlist_show', 'lte-rrc_ue_capabilityrat_containerlist_value', 'lte-rrc_ue_capabilityrat_containerlist_size', 'lte-rrc_ue_capabilityrat_containerlist_pos', 'lte-rrc_ue_capabilityrequest_show', 'lte-rrc_ue_capabilityrequest_value', 'lte-rrc_ue_capabilityrequest_size', 'lte-rrc_ue_capabilityrequest_pos', 'lte-rrc_ue_category_show', 'lte-rrc_ue_category_value', 'lte-rrc_ue_category_size', 'lte-rrc_ue_category_pos', 'lte-rrc_ue_category_v1020_show', 'lte-rrc_ue_category_v1020_value', 'lte-rrc_ue_category_v1020_size', 'lte-rrc_ue_category_v1020_pos', 'lte-rrc_ue_category_v1170_show', 'lte-rrc_ue_category_v1170_value', 'lte-rrc_ue_category_v1170_size', 'lte-rrc_ue_category_v1170_pos', 'lte-rrc_ue_categorydl_r12_show', 'lte-rrc_ue_categorydl_r12_value', 'lte-rrc_ue_categorydl_r12_size', 'lte-rrc_ue_categorydl_r12_pos', 'lte-rrc_ue_categoryul_r12_show', 'lte-rrc_ue_categoryul_r12_value', 'lte-rrc_ue_categoryul_r12_size', 'lte-rrc_ue_categoryul_r12_pos', 'lte-rrc_ue_identity_show', 'lte-rrc_ue_identity_value', 'lte-rrc_ue_identity_size', 'lte-rrc_ue_identity_pos', 'lte-rrc_ue_specificrefsigssupported_show', 'lte-rrc_ue_specificrefsigssupported_value', 'lte-rrc_ue_specificrefsigssupported_size', 'lte-rrc_ue_specificrefsigssupported_pos', 'lte-rrc_ue_transmitantennaselection_show', 'lte-rrc_ue_transmitantennaselection_value', 'lte-rrc_ue_transmitantennaselection_size', 'lte-rrc_ue_transmitantennaselection_pos', 'lte-rrc_ue_txantennase

In [ ]:
for col in mixed_cols:
    print("\n==========================")
    print(f"Column: {col}")
    
    # Count each Python type
    type_counts = attack_dataset_clean[col].apply(lambda x: type(x).__name__).value_counts()
    print("Types found:\n", type_counts)
    
    # Show up to 5 example values
    print("\nExample values:")
    print(attack_dataset_clean[col].head(10).to_list())   # you can increase or decrease number

==========================
Column: e212_gummei_mcc_show
Types found:
 e212_gummei_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mcc_value
Types found:
 e212_gummei_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mcc_size
Types found:
 e212_gummei_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mcc_pos
Types found:
 e212_gummei_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_show
Types found:
 e212_gummei_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_value
Types found:
 e212_gummei_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_size
Types found:
 e212_gummei_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_pos
Types found:
 e212_gummei_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_imsi_show
Types found:
 e212_imsi_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_imsi_value
Types found:
 e212_imsi_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: e212_imsi_size
Types found:
 e212_imsi_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_imsi_pos
Types found:
 e212_imsi_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_show
Types found:
 e212_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_value
Types found:
 e212_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_size
Types found:
 e212_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_pos
Types found:
 e212_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_show
Types found:
 e212_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_value
Types found:
 e212_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_size
Types found:
 e212_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_pos
Types found:
 e212_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_show
Types found:
 e212_tai_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_value
Types found:
 e212_tai_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_size
Types found:
 e212_tai_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_pos
Types found:
 e212_tai_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_show
Types found:
 e212_tai_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_value
Types found:
 e212_tai_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_size
Types found:
 e212_tai_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_pos
Types found:
 e212_tai_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_show
Types found:
 gsm_a_dtap_autn_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_value
Types found:
 gsm_a_dtap_autn_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_autn_size
Types found:
 gsm_a_dtap_autn_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_pos
Types found:
 gsm_a_dtap_autn_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_show
Types found:
 gsm_a_dtap_autn_amf_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_value
Types found:
 gsm_a_dtap_autn_amf_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_size
Types found:
 gsm_a_dtap_autn_amf_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_pos
Types found:
 gsm_a_dtap_autn_amf_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_mac_show
Types found:
 gsm_a_dtap_autn_mac_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_mac_value
Types found:
 gsm_a_dtap_autn_mac_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_autn_mac_size
Types found:
 gsm_a_dtap_autn_mac_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_mac_pos
Types found:
 gsm_a_dtap_autn_mac_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_show
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_value
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_size
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_pos
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_rand_show
Types found:
 gsm_a_dtap_rand_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_rand_value
Types found:
 gsm_a_dtap_rand_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_rand_size
Types found:
 gsm_a_dtap_rand_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_rand_pos
Types found:
 gsm_a_dtap_rand_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_show
Types found:
 gsm_a_ie_mobileid_type_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_value
Types found:
 gsm_a_ie_mobileid_type_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_size
Types found:
 gsm_a_ie_mobileid_type_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_pos
Types found:
 gsm_a_ie_mobileid_type_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_imeisv_show
Types found:
 gsm_a_imeisv_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_imeisv_value
Types found:
 gsm_a_imeisv_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_imeisv_size
Types found:
 gsm_a_imeisv_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_imeisv_pos
Types found:
 gsm_a_imeisv_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_key_seq_show
Types found:
 gsm_a_key_seq_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_key_seq_value
Types found:
 gsm_a_key_seq_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_key_seq_size
Types found:
 gsm_a_key_seq_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_key_seq_pos
Types found:
 gsm_a_key_seq_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_l3_protocol_discriminator_show
Types found:
 gsm_a_l3_protocol_discriminator_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_l3_protocol_discriminator_value
Types found:
 gsm_a_l3_protocol_discriminator_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_l3_protocol_discriminator_size
Types found:
 gsm_a_l3_protocol_discriminator_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_l3_protocol_discriminator_pos
Types found:
 gsm_a_l3_protocol_discriminator_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_lac_show
Types found:
 gsm_a_lac_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_lac_value
Types found:
 gsm_a_lac_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_lac_size
Types found:
 gsm_a_lac_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_lac_pos
Types found:
 gsm_a_lac_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_oddevenind_show
Types found:
 gsm_a_oddevenind_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_oddevenind_value
Types found:
 gsm_a_oddevenind_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_oddevenind_size
Types found:
 gsm_a_oddevenind_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_oddevenind_pos
Types found:
 gsm_a_oddevenind_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_skip_ind_show
Types found:
 gsm_a_skip_ind_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_skip_ind_value
Types found:
 gsm_a_skip_ind_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_skip_ind_size
Types found:
 gsm_a_skip_ind_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_skip_ind_pos
Types found:
 gsm_a_skip_ind_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_accessstratumrelease_show
Types found:
 lte-rrc_accessstratumrelease_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_accessstratumrelease_value
Types found:
 lte-rrc_accessstratumrelease_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_accessstratumrelease_size
Types found:
 lte-rrc_accessstratumrelease_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_accessstratumrelease_pos
Types found:
 lte-rrc_accessstratumrelease_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_alpha_show
Types found:
 lte-rrc_alpha_show
int    6532
Name: count, dtype: int64

Example values:
[7, -1, 5, -1, 7, -1, 7, -1, 7, 7]

==========================
Column: lte-rrc_alpha_value
Types found:
 lte-rrc_alpha_value
int    6532
Name: count, dtype: int64

Example values:
[118, -1, 43, -1, 234, -1, 234, -1, 234, 234]

==========================
Column: lte-rrc_alpha_size
Types found:
 lte-rrc_alpha_size
int    6532
Name: count, dtype: int64

Example values:
[1, -1, 1, -1, 1, -1, 1, -1, 1, 1]

==========================
Column: lte-rrc_alpha_pos
Types found:
 lte-rrc_alpha_pos
int    6532
Name: count, dtype: int64

Example values:
[63, -1, 64, -1, 63, -1, 63, -1, 63, 63]

==========================
Column: lte-rrc_alternativetbs_indices_r12_show
Types found:
 lte-rrc_alternativetbs_indices_r12_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_alternativetbs_indices_r12_value
Types found:
 lte-rrc_alternativetbs_indices_r12_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_alternativetbs_indices_r12_size
Types found:
 lte-rrc_alternativetbs_indices_r12_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_alternativetbs_indices_r12_pos
Types found:
 lte-rrc_alternativetbs_indices_r12_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_bandcombinationlisteutra_r10_show
Types found:
 lte-rrc_bandcombinationlisteutra_r10_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_bandcombinationlisteutra_r10_value
Types found:
 lte-rrc_bandcombinationlisteutra_r10_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: lte-rrc_bandcombinationlisteutra_r10_size
Types found:
 lte-rrc_bandcombinationlisteutra_r10_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_bandcombinationlisteutra_r10_pos
Types found:
 lte-rrc_bandcombinationlisteutra_r10_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_bandcombinationparameters_r10_show
Types found:
 lte-rrc_bandcombinationparameters_r10_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_bandcombinationparameters_r10_value
Types found:
 lte-rrc_bandcombinationparameters_r10_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: lte-rrc_bandcombinationparameters_r10_size
Types found:
 lte-rrc_bandcombinationparameters_r10_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_bandcombinationparameters_r10_pos
Types found:
 lte-rrc_bandcombinationparameters_r10_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_c1_show
Types found:
 lte-rrc_c1_show
int    6532
Name: count, dtype: int64

Example values:
[0, 1, 0, 1, 0, 1, 0, 1, 0, 0]

==========================
Column: lte-rrc_c1_value
Types found:
 lte-rrc_c1_value
float    6532
Name: count, dtype: int64

Example values:
[3.3867559660601674, 3.464371937181019, 3.433510827367448, 3.5823271752869816, 3.37849360797723, 3.578992287387246, 3.3613113909585692, 3.428077417400887, 3.339862082259782, 3.339862082259782]

==========================
Column: lte-rrc_c1_size
Types found:
 lte-rrc_c1_size
int    6532
Name: count, dtype: int64

Example values:
[36, 27, 43, 33, 47, 34, 47, 31, 47, 47]

==========================
Column: lte-rrc_c1_pos
Types found:
 lte-rrc_c1_pos
int    6532
Name: count, dtype: int64

Example values:
[44, 44, 44, 44, 44, 44, 44, 44, 44, 44]

==========================
Column: lte-rrc_c_rnti_show
Types found:
 lte-rrc_c_rnti_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: lte-rrc_c_rnti_value
Types found:
 lte-rrc_c_rnti_value
int    6532

In [ ]:
LONG_THRESHOLD = 10   # adjust this for your dataset

for col in mixed_cols:
    print("\n==========================")
    print(f"Column: {col}")

    # Count each Python type
    type_counts = attack_dataset_clean[col].apply(lambda x: type(x).__name__).value_counts()
    print("Types found:\n", type_counts)

    # Show some normal example values
    print("\nExample values:")
    print(attack_dataset_clean[col].head(50).to_list())

    # Find long payloads
    long_mask = attack_dataset_clean[col].apply(
        lambda x: isinstance(x, str) and len(str(x)) >= LONG_THRESHOLD
    )

    long_values = attack_dataset_clean.loc[long_mask, col]

    print(f"\nLong payload values (len >= {LONG_THRESHOLD}): {len(long_values)} found")

    # Show the first few long payloads
    print(long_values.head(10).to_list())

==========================
Column: e212_gummei_mcc_show
Types found:
 e212_gummei_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mcc_value
Types found:
 e212_gummei_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 241, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mcc_size
Types found:
 e212_gummei_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mcc_pos
Types found:
 e212_gummei_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 61, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mnc_show
Types found:
 e212_gummei_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mnc_value
Types found:
 e212_gummei_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 61712, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mnc_size
Types found:
 e212_gummei_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_gummei_mnc_pos
Types found:
 e212_gummei_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_imsi_show
Types found:
 e212_imsi_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_imsi_value
Types found:
 e212_imsi_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_imsi_size
Types found:
 e212_imsi_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_imsi_pos
Types found:
 e212_imsi_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mcc_show
Types found:
 e212_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mcc_value
Types found:
 e212_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mcc_size
Types found:
 e212_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mcc_pos
Types found:
 e212_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mnc_show
Types found:
 e212_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mnc_value
Types found:
 e212_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mnc_size
Types found:
 e212_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_mnc_pos
Types found:
 e212_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mcc_show
Types found:
 e212_tai_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mcc_value
Types found:
 e212_tai_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 241, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mcc_size
Types found:
 e212_tai_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mcc_pos
Types found:
 e212_tai_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 121, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mnc_show
Types found:
 e212_tai_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mnc_value
Types found:
 e212_tai_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 61712, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mnc_size
Types found:
 e212_tai_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: e212_tai_mnc_pos
Types found:
 e212_tai_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 122, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_show
Types found:
 gsm_a_dtap_autn_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_value
Types found:
 gsm_a_dtap_autn_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_size
Types found:
 gsm_a_dtap_autn_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_pos
Types found:
 gsm_a_dtap_autn_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_amf_show
Types found:
 gsm_a_dtap_autn_amf_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_amf_value
Types found:
 gsm_a_dtap_autn_amf_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_amf_size
Types found:
 gsm_a_dtap_autn_amf_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_amf_pos
Types found:
 gsm_a_dtap_autn_amf_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_mac_show
Types found:
 gsm_a_dtap_autn_mac_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_mac_value
Types found:
 gsm_a_dtap_autn_mac_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_mac_size
Types found:
 gsm_a_dtap_autn_mac_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_mac_pos
Types found:
 gsm_a_dtap_autn_mac_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_show
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_value
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_size
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_pos
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_rand_show
Types found:
 gsm_a_dtap_rand_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_rand_value
Types found:
 gsm_a_dtap_rand_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_rand_size
Types found:
 gsm_a_dtap_rand_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_dtap_rand_pos
Types found:
 gsm_a_dtap_rand_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_ie_mobileid_type_show
Types found:
 gsm_a_ie_mobileid_type_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

Long payload values (len >= 10): 0 found
[]

==========================
Column: gsm_a_ie_mobileid_type_value
Types found:
 gsm_a_ie_mobileid_type_value
int    6532
Name: count, dtype: int64

Example values:

In [ ]:
# import math

# def convert_hex_hybrid(x):
#     # Keep -1 exactly as is
#     if x == -1 or x == "-1":
#         return -1

#     # Convert to string
#     s = str(x).strip()

#     # Empty or NaN
#     if s == "" or s.lower() == "nan":
#         return -1

#     # Remove 0x prefix
#     if s.startswith("0x") or s.startswith("0X"):
#         s = s[2:]

#     # Check if value is hex
#     if not all(c in "0123456789abcdefABCDEF" for c in s):
#         return -1

#     # If hex string is short, safe to convert to int
#     if len(s) < 10:
#         try:
#             return int(s, 16)    # convert safely
#         except:
#             return -1

#     # If hex string is long, compute entropy instead
#     freq = {c: s.count(c) for c in set(s)}
#     total = len(s)
#     entropy = -sum((v/total) * math.log2(v/total) for v in freq.values())

#     return entropy

In [ ]:
# for col in mixed_cols:
#     normal_dataset_clean[col] = normal_dataset_clean[col].apply(convert_hex_hybrid)
#     attack_dataset_clean[col] = attack_dataset_clean[col].apply(convert_hex_hybrid)

In [ ]:
print(type(attack_dataset_clean))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
normal_dataset_clean.to_csv("../dataset/clean/normal_dataset.csv", index=False)
attack_dataset_clean.to_csv("../dataset/clean/attack_dataset.csv", index=False)

In [ ]:
for col in mixed_cols:
    print("\n==========================")
    print(f"Column: {col}")
    
    # Count each Python type
    type_counts = attack_dataset_clean[col].apply(lambda x: type(x).__name__).value_counts()
    print("Types found:\n", type_counts)
    
    # Show up to 5 example values
    print("\nExample values:")
    print(attack_dataset_clean[col].head(50).to_list())   # you can increase or decrease number

==========================
Column: e212_gummei_mcc_show
Types found:
 e212_gummei_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mcc_value
Types found:
 e212_gummei_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 241, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mcc_size
Types found:
 e212_gummei_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mcc_pos
Types found:
 e212_gummei_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 61, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_show
Types found:
 e212_gummei_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_value
Types found:
 e212_gummei_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 61712, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_size
Types found:
 e212_gummei_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_gummei_mnc_pos
Types found:
 e212_gummei_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 62, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_imsi_show
Types found:
 e212_imsi_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_imsi_value
Types found:
 e212_imsi_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: e212_imsi_size
Types found:
 e212_imsi_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_imsi_pos
Types found:
 e212_imsi_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_show
Types found:
 e212_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_value
Types found:
 e212_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_size
Types found:
 e212_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mcc_pos
Types found:
 e212_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_show
Types found:
 e212_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_value
Types found:
 e212_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_size
Types found:
 e212_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_mnc_pos
Types found:
 e212_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_show
Types found:
 e212_tai_mcc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_value
Types found:
 e212_tai_mcc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 241, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_size
Types found:
 e212_tai_mcc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mcc_pos
Types found:
 e212_tai_mcc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 121, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_show
Types found:
 e212_tai_mnc_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_value
Types found:
 e212_tai_mnc_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 61712, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_size
Types found:
 e212_tai_mnc_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: e212_tai_mnc_pos
Types found:
 e212_tai_mnc_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 122, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_show
Types found:
 gsm_a_dtap_autn_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_value
Types found:
 gsm_a_dtap_autn_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_autn_size
Types found:
 gsm_a_dtap_autn_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_pos
Types found:
 gsm_a_dtap_autn_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_show
Types found:
 gsm_a_dtap_autn_amf_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_value
Types found:
 gsm_a_dtap_autn_amf_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_size
Types found:
 gsm_a_dtap_autn_amf_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_amf_pos
Types found:
 gsm_a_dtap_autn_amf_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_mac_show
Types found:
 gsm_a_dtap_autn_mac_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_mac_value
Types found:
 gsm_a_dtap_autn_mac_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_autn_mac_size
Types found:
 gsm_a_dtap_autn_mac_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_mac_pos
Types found:
 gsm_a_dtap_autn_mac_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_show
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_value
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_size
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_autn_sqn_xor_ak_pos
Types found:
 gsm_a_dtap_autn_sqn_xor_ak_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_rand_show
Types found:
 gsm_a_dtap_rand_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_rand_value
Types found:
 gsm_a_dtap_rand_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_dtap_rand_size
Types found:
 gsm_a_dtap_rand_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_dtap_rand_pos
Types found:
 gsm_a_dtap_rand_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_show
Types found:
 gsm_a_ie_mobileid_type_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_value
Types found:
 gsm_a_ie_mobileid_type_value
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_size
Types found:
 gsm_a_ie_mobileid_type_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_ie_mobileid_type_pos
Types found:
 gsm_a_ie_mobileid_type_pos
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_imeisv_show
Types found:
 gsm_a_imeisv_show
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_imeisv_value
Types found:
 gsm_a_imeisv_value
float    6532
Name: count, dtype: int64

Example values:
[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]

==========================
Column: gsm_a_imeisv_size
Types found:
 gsm_a_imeisv_size
int    6532
Name: count, dtype: int64

Example values:
[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]

==========================
Column: gsm_a_imeisv_pos
Types found:
 gsm_a_imeisv_pos
int    6532
Name: count, dtype: int64

Example values:

## AI Detection Dataset — EDA (ai_normal / ai_attack)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

DATASET_DIR = Path("../dataset")
NORMAL_DIR = DATASET_DIR / "ai_normal"
ATTACK_DIR = DATASET_DIR / "ai_attack"

def _load_folder(folder: Path, label: int) -> pd.DataFrame:
    dfs = []
    for p in sorted(folder.glob("*_essential.csv")):
        df = pd.read_csv(p)
        extra = pd.DataFrame({"label": label, "source": p.name}, index=df.index)
        dfs.append(pd.concat([df, extra], axis=1))
    return pd.concat(dfs, ignore_index=True) if dfs else pd.DataFrame()

normal_df = _load_folder(NORMAL_DIR, label=0)
attack_df = _load_folder(ATTACK_DIR, label=1)
dataset   = pd.concat([normal_df, attack_df], ignore_index=True)

print(f"Normal files  : {normal_df['source'].nunique()}  |  rows: {len(normal_df)}")
print(f"Attack files  : {attack_df['source'].nunique()}  |  rows: {len(attack_df)}")
print(f"Total columns : {dataset.shape[1]}")

### 1. Class distribution and per-file row counts

In [ ]:
# Class imbalance overview
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Left: overall class counts
axes[0].bar(["Normal", "Attack"], [len(normal_df), len(attack_df)], color=["steelblue", "tomato"])
axes[0].set_title("Raw class counts (before balancing)")
axes[0].set_ylabel("Rows")
for i, v in enumerate([len(normal_df), len(attack_df)]):
    axes[0].text(i, v + 200, str(v), ha="center")

# Right: attack rows per file (sorted)
attack_counts = attack_df.groupby("source").size().sort_values(ascending=False)
attack_counts.plot(kind="bar", ax=axes[1], color="tomato")
axes[1].set_title(f"Rows per attack type ({attack_df['source'].nunique()} types)")
axes[1].set_xlabel("")
axes[1].tick_params(axis="x", labelsize=6, rotation=90)
axes[1].set_ylabel("Rows")

plt.tight_layout()
plt.show()

print("Normal rows per file:")
print(normal_df.groupby("source").size().sort_values(ascending=False).to_string())

### 2. Feature sparsity (missing sentinel = -1)

In [ ]:
value_cols = [c for c in dataset.columns if c.endswith("_value")]
missing_pct = (dataset[value_cols] == -1).mean().sort_values()

print(f"Total _value columns : {len(value_cols)}")
for t in [0.50, 0.80, 0.90, 0.95, 0.99]:
    n = (missing_pct > t).sum()
    print(f"  >{t*100:.0f}% missing: {n:3d}  ({n/len(value_cols)*100:.1f}%)")

kept = missing_pct[missing_pct <= 0.95]
print(f"\nColumns kept (≤95% missing): {len(kept)}")
print(kept.index.tolist())

# Distribution of per-column missing rates
plt.figure(figsize=(8, 4))
plt.hist(missing_pct * 100, bins=30, color="steelblue", edgecolor="white")
plt.axvline(95, color="tomato", linestyle="--", label="95% threshold")
plt.xlabel("% missing (-1) per column")
plt.ylabel("Number of columns")
plt.title("Sparsity distribution across _value columns")
plt.legend()
plt.tight_layout()
plt.show()

### 3. Kept feature analysis — mean by class and discriminative power

In [ ]:
kept_cols = missing_pct[missing_pct <= 0.95].index.tolist()

rows = []
for col in kept_cols:
    v_n = dataset.loc[dataset["label"] == 0, col].replace(-1, np.nan).dropna()
    v_a = dataset.loc[dataset["label"] == 1, col].replace(-1, np.nan).dropna()
    rows.append({
        "feature": col,
        "missing_%": round(missing_pct[col] * 100, 1),
        "normal_mean": round(v_n.mean(), 3) if len(v_n) else np.nan,
        "attack_mean": round(v_a.mean(), 3) if len(v_a) else np.nan,
        "normal_std":  round(v_n.std(), 3)  if len(v_n) else np.nan,
        "attack_std":  round(v_a.std(), 3)  if len(v_a) else np.nan,
    })

feat_df = pd.DataFrame(rows).set_index("feature")
print(feat_df.to_string())

# packet_type and direction (signal columns kept in preprocessing)
print("\n--- packet_type ---")
print(dataset.groupby(["label", "packet_type"]).size().unstack(fill_value=0))
print("\n--- direction ---")
print(dataset.groupby(["label", "direction"]).size().unstack(fill_value=0))

### 4. Duplicate row count

In [ ]:
dedup_cols = [c for c in dataset.columns if c not in ("source", "label")]
n_dupes = dataset.duplicated(subset=dedup_cols).sum()
print(f"Duplicate rows in full dataset: {n_dupes} / {len(dataset)} ({n_dupes/len(dataset)*100:.1f}%)")
print("(removed before train/test split in fbs_detection_rf.ipynb)")